Deactivated because of new repository

diff --git a/.github/workflows/browserstack-tests.yml b/.github/workflows/browserstack-tests.yml
--- a/.github/workflows/browserstack-tests.yml
+++ b/.github/workflows/browserstack-tests.yml
@@ -66,47 +66,47 @@ jobs:
           echo "DMS_ENV=$DMS_ENV" >> $GITHUB_ENV
           echo "CRS_ENV=$CRS_ENV" >> $GITHUB_ENV
 
-      - name: Run specified test cases
-        env:
-          TEST_ENV: ${{ env.TEST_ENV }}
-          EMMA_ENV: ${{ env.EMMA_ENV }}
-          UMS_ENV: ${{ env.UMS_ENV }}
-          BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
-          BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
-          TESTRAIL_USERNAME: ${{ secrets.TESTRAIL_USERNAME }}
-          TESTRAIL_API_KEY: ${{ secrets.TESTRAIL_API_KEY }}
-        run: |
-          TEST_CASES="${{ github.event.inputs.test_case || 'all' }}" # Default to 'all' if no input
-          echo "Executing in environment: $TEST_ENV"
-          echo "EMMA is running in environment: $EMMA_ENV"
-          echo "User Management Service (UMS) is running in environment: $UMS_ENV"
-          echo "Test case(s) input: $TEST_CASES"
+      # - name: Run specified test cases
+      #   env:
+      #     TEST_ENV: ${{ env.TEST_ENV }}
+      #     EMMA_ENV: ${{ env.EMMA_ENV }}
+      #     UMS_ENV: ${{ env.UMS_ENV }}
+      #     BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
+      #     BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
+      #     TESTRAIL_USERNAME: ${{ secrets.TESTRAIL_USERNAME }}
+      #     TESTRAIL_API_KEY: ${{ secrets.TESTRAIL_API_KEY }}
+      #   run: |
+      #     TEST_CASES="${{ github.event.inputs.test_case || 'all' }}" # Default to 'all' if no input
+      #     echo "Executing in environment: $TEST_ENV"
+      #     echo "EMMA is running in environment: $EMMA_ENV"
+      #     echo "User Management Service (UMS) is running in environment: $UMS_ENV"
+      #     echo "Test case(s) input: $TEST_CASES"
           
-          ERRORS=0
+      #     ERRORS=0
 
-          if [ -z "$TEST_CASES" ] || [ "$TEST_CASES" = "all" ]; then
-            echo "Running all tests..."
-            node run-all-tests.js || ERRORS=$((ERRORS+1))
-          else
-            IFS=',' read -ra TEST_ARRAY <<< "$TEST_CASES" # Split by comma
-            for TEST_CASE in "${TEST_ARRAY[@]}"; do
-              TEST_CASE=$(echo "$TEST_CASE" | xargs) # Trim spaces
-              if [ -f "testCases/$TEST_CASE.js" ]; then
-                echo "Found file: testCases/$TEST_CASE.js"
-                chmod +x testCases/$TEST_CASE.js
-                echo "Executing test case $TEST_CASE..."
-                node -e "require('./testCases/$TEST_CASE')();" || ERRORS=$((ERRORS+1))
-                echo "Execution of $TEST_CASE.js completed with status $?"
-              else
-                echo "Test case not found: $TEST_CASE"
-                ERRORS=$((ERRORS+1))
-              fi
-            done
-          fi
+      #     if [ -z "$TEST_CASES" ] || [ "$TEST_CASES" = "all" ]; then
+      #       echo "Running all tests..."
+      #       node run-all-tests.js || ERRORS=$((ERRORS+1))
+      #     else
+      #       IFS=',' read -ra TEST_ARRAY <<< "$TEST_CASES" # Split by comma
+      #       for TEST_CASE in "${TEST_ARRAY[@]}"; do
+      #         TEST_CASE=$(echo "$TEST_CASE" | xargs) # Trim spaces
+      #         if [ -f "testCases/$TEST_CASE.js" ]; then
+      #           echo "Found file: testCases/$TEST_CASE.js"
+      #           chmod +x testCases/$TEST_CASE.js
+      #           echo "Executing test case $TEST_CASE..."
+      #           node -e "require('./testCases/$TEST_CASE')();" || ERRORS=$((ERRORS+1))
+      #           echo "Execution of $TEST_CASE.js completed with status $?"
+      #         else
+      #           echo "Test case not found: $TEST_CASE"
+      #           ERRORS=$((ERRORS+1))
+      #         fi
+      #       done
+      #     fi
 
-          if [ $ERRORS -ne 0 ]; then
-            echo "$ERRORS test(s) failed."
-            exit 1
-          else
-            echo "All tests passed successfully."
-          fi
+      #     if [ $ERRORS -ne 0 ]; then
+      #       echo "$ERRORS test(s) failed."
+      #       exit 1
+      #     else
+      #       echo "All tests passed successfully."
+      #     fi
